### ISSUE TITLE
Is data completed？

### ISSUE THREAD

**Issue by cdhx** [zaibacu/thesaurus#1]
There is only 169K word，how did you get this json, it sames is not a complete dataset of thesaurus

**Comment by zaibacu** [comment]
Hello, this is an extract from [WordNet](https://wordnet.princeton.edu/download/current-version). It does have a history of being incomplete for other languages, so it might be for English as well.

**Comment by cdhx** [comment]
sorry,  I thought it is a offline version of this website, whose name is exactly "thesaurus", so I mean "thesaurus" is this website
https://www.thesaurus.com/browse/developer
