### ISSUE TITLE
Need a dummy example for usage of wordnet extractor

### ISSUE THREAD

**Issue by HSB1821** [zaibacu/thesaurus#3]
Hi, I was trying to run the script but I am unable to. Can  you provide a example for  running the extractor in the readme.I have tried different combinations.

**Comment by zaibacu** [comment]
Hello, can you give an error you're receiving?

**Comment by HSB1821** [comment]
> Hello, can you give an error you're receiving?

The error is , "unrecognised arguments"
I have tried different combinations of it but to no avail.

**Comment by zaibacu** [comment]
Ok, so little bit more documented usage:

1. Download database, [Wordnet](https://wordnetcode.princeton.edu/wn3.1.dict.tar.gz) (CLI: `curl  https://wordnetcode.princeton.edu/wn3.1.dict.tar.gz > wordnet.tar.gz`)
2. Extract it (CLI: `tar -xzf wordnet.tar.gz`)
3. Now we can execute wordnet extract. If following command above, dictionary is extracted to folder `dict`, so `python wordnet_extract.py --db_path=./dict result.jsonl`
4. `result.jsonl` contains fresh dictionary.

This approach would work with other languages, but only if they follow same format

**Comment by HSB1821** [comment]
> Ok, so little bit more documented usage:
> 
> 1. Download database, [Wordnet](https://wordnetcode.princeton.edu/wn3.1.dict.tar.gz) (CLI: `curl  https://wordnetcode.princeton.edu/wn3.1.dict.tar.gz > wordnet.tar.gz`)
> 2. Extract it (CLI: `tar -xzf wordnet.tar.gz`)
> 3. Now we can execute wordnet extract. If following command above, dictionary is extracted to folder `dict`, so `python wordnet_extract.py --db_path=./dict result.jsonl`
> 4. `result.jsonl` contains fresh dictionary.
> 
> This approach would work with other languages, but only if they follow same format

Apologies for replying so late,  It worked flawlessly. Many thanks for taking time out  to help me.
Just wanted to share an observation the old jsonl file is around 18MB but the new generated one is 12MB , maybe  they reduced words or something.
Once  thanks for helping me, this is a great repo.

**Comment by zaibacu** [comment]
Old was generated long time ago (5years), there were few versions. It's possible that some words were removed :) Thanks for letting me know, I will try to check which words are missing
